collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8996416
  brandStrength: 0.7240143
  lightness: 0.9014337
  brandColors:
    - '#333335'
    - '#939997'
    - '#8F6F5F'
    - '#F6BA73'
    - '#FEFA9B'
  rhythmicContrast: 0.874552
typography_spectrum: 0.3566308
layout_spectrum: 0.3315412
name: The Maslow Experiment
